name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t oversightdatascrapercr.azurecr.io/oversight-data-scraper:v1 .
    - name: Push to Azure CR
      run: docker push oversightdatascrapercr.azurecr.io/oversight-data-scraper:v1
